# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  pokemonapi:
    image: pokemonapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 5001:5000
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "<PokemonPassw0rd>"
      ACCEPT_EULA: "Y"
    ports: 
      - 1433:1433 
    volumes: 
      - E:\db\pokemon:/var/opt/mssql/data
